version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translator-ai-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app:cached
    ports:
      - "8001:8000"
    env_file:
      - ./.env.dev.container
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend

  db:
    image: postgres:17
    container_name: translator-ai-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=canibal
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
