version: '3.9'

services:

  db_container:
    image: postgres:17
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  web:
    build: .
    environment:
      - IS_DEVELOPMENT_ENV=FALSE
    container_name: translator-ai-web
    depends_on:
      - db_container   
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod
  
  webser_container:
    image: nginx:1.27.5
    container_name: webserver
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - web
        
volumes:
  postgres_data:
