version: '3.9'

services:

  db:
    image: postgres:17
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod.container

  web:
    build: .
    container_name: translator-ai-web
    depends_on:
      - db    
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod.container
    ports:
      - "8000:8000"              # Gunicorn
      - "5678:5678"              # debugpy listener
    command: [ "sh", "./entrypoint.debug.sh" ]
  
  frontend-proxy:
    image: nginx:1.27.5
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - web
        
volumes:
  postgres_data:

