# Generated by Django 5.1.6 on 2025-05-08 11:33

import django.db.models.deletion
import xliff_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lang_iso_value', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_iso_value', models.CharField(blank=True, max_length=10, null=True)),
                ('emoji_flag', models.CharField(default='🌎', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, null=True)),
                ('date_last_modification', models.DateTimeField(auto_now=True)),
                ('user_last_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.languages')),
                ('project', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.projects')),
            ],
            options={
                'ordering': ['-date_last_modification'],
            },
        ),
        migrations.CreateModel(
            name='ReviewRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_xliff_file', models.FileField(blank=True, upload_to='')),
                ('info_tag', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed_by_business', models.DateTimeField(blank=True, null=True)),
                ('date_declined', models.DateTimeField(blank=True, null=True)),
                ('decline_justification', models.TextField(blank=True, null=True)),
                ('requester_comment', models.TextField(blank=True, null=True)),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Requested', max_length=100)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_receiver', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.languages')),
                ('project', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.projects')),
                ('technical_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Translations_Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.TextField()),
                ('reviewer_comment', models.TextField(blank=True, null=True)),
                ('source', models.TextField()),
                ('ai_translation', models.TextField(blank=True, null=True)),
                ('reviewer_translation', models.TextField()),
                ('date_ingested', models.DateTimeField(blank=True, null=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.languages')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.reviewrequests')),
            ],
        ),
        migrations.CreateModel(
            name='TranslationsRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_xliff_file', models.FileField(upload_to=xliff_manager.models.TranslationsRequests.upload_to_folder)),
                ('target_xliff_file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prompt_addition_file', models.FileField(upload_to=xliff_manager.models.TranslationsRequests.upload_to_folder)),
                ('literals_to_exclude_file', models.FileField(upload_to=xliff_manager.models.TranslationsRequests.upload_to_folder)),
                ('literalpatterns_to_exclude_file', models.FileField(upload_to=xliff_manager.models.TranslationsRequests.upload_to_folder)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_started_on_llm', models.DateTimeField(blank=True, null=True)),
                ('date_received_from_llm', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Created', max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.languages')),
                ('project', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.projects')),
                ('request_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_requested', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.projects')),
                ('review_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.reviewrequests')),
                ('translation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.translationsrequests')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xliff_manager.projects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
