# Generated by Django 5.1.6 on 2025-02-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='emoji_flag',
            field=models.CharField(default='🌎', max_length=10),
        ),
        migrations.AlterField(
            model_name='languages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='translations',
            name='salesforce_id',
            field=models.TextField(),
        ),
    ]
