# Generated by Django 5.1.6 on 2025-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0002_languages_emoji_flag_alter_languages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translations',
            name='date_modified',
            field=models.DateTimeField(),
        ),
    ]
