# Generated by Django 5.1.6 on 2025-02-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0003_alter_translations_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='translations',
            name='date_ingested',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
