# Generated by Django 5.1.6 on 2025-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0004_translations_date_ingested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translations',
            name='date_ingested',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translations',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
