# Generated by Django 5.1.6 on 2025-02-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0005_alter_translations_date_ingested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationsRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xliff_file', models.FileField(upload_to='xliff_files/')),
                ('prompt_addition_file', models.FileField(upload_to='prompt_addition_files/')),
                ('literals_to_exclude_file', models.FileField(upload_to='literals_to_exclude_files/')),
                ('literal_patterns_to_exclude_file', models.FileField(upload_to='literal_patterns_to_exclude_files/')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.languages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.customuser')),
            ],
        ),
    ]
