# Generated by Django 5.1.6 on 2025-02-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0006_translationsrequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationsrequests',
            name='literal_patterns_to_exclude_file',
            field=models.FileField(upload_to='translations_requests'),
        ),
        migrations.AlterField(
            model_name='translationsrequests',
            name='literals_to_exclude_file',
            field=models.FileField(upload_to='translations_requests'),
        ),
        migrations.AlterField(
            model_name='translationsrequests',
            name='prompt_addition_file',
            field=models.FileField(upload_to='translations_requests'),
        ),
        migrations.AlterField(
            model_name='translationsrequests',
            name='xliff_file',
            field=models.FileField(upload_to='translations_requests'),
        ),
    ]
