# Generated by Django 5.1.6 on 2025-02-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0007_alter_translationsrequests_literal_patterns_to_exclude_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationsrequests',
            old_name='literal_patterns_to_exclude_file',
            new_name='literalpatterns_to_exclude_file',
        ),
    ]
