# Generated by Django 5.1.6 on 2025-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0008_rename_literal_patterns_to_exclude_file_translationsrequests_literalpatterns_to_exclude_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationsrequests',
            old_name='xliff_file',
            new_name='source_xliff_file',
        ),
        migrations.AddField(
            model_name='translationsrequests',
            name='target_xliff_file',
            field=models.CharField(default='target_file', max_length=200),
            preserve_default=False,
        ),
    ]
