# Generated by Django 5.1.6 on 2025-03-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0009_rename_xliff_file_translationsrequests_source_xliff_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationsrequests',
            old_name='date_requested',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='translationsrequests',
            name='date_sent_to_llm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationsrequests',
            name='status',
            field=models.CharField(default='Created', max_length=100),
        ),
    ]
