# Generated by Django 5.1.6 on 2025-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0010_rename_date_requested_translationsrequests_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationsrequests',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationsrequests',
            name='date_received_from_llm',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
