# Generated by Django 5.1.6 on 2025-03-05 09:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0011_translationsrequests_date_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationsrequests',
            old_name='date_completed',
            new_name='date_business_reviewed',
        ),
        migrations.RemoveField(
            model_name='translationsrequests',
            name='user',
        ),
        migrations.AddField(
            model_name='translationsrequests',
            name='business_reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_reviewer', to='xliff_manager.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translationsrequests',
            name='date_pending_business_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translationsrequests',
            name='technical_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technical_user', to='xliff_manager.customuser'),
            preserve_default=False,
        ),
    ]
