# Generated by Django 5.1.6 on 2025-03-05 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0012_rename_date_completed_translationsrequests_date_business_reviewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationsrequests',
            name='business_reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_reviewer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='translationsrequests',
            name='technical_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
