# Generated by Django 5.1.6 on 2025-03-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0013_alter_translationsrequests_business_reviewer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationsrequests',
            name='business_reviewer',
        ),
    ]
