# Generated by Django 5.1.6 on 2025-03-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0014_remove_translationsrequests_business_reviewer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Translations',
            new_name='Translations_Units',
        ),
    ]
