# Generated by Django 5.1.6 on 2025-03-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0015_rename_translations_translations_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationsrequests',
            name='date_business_reviewed',
        ),
        migrations.RemoveField(
            model_name='translationsrequests',
            name='date_pending_business_review',
        ),
    ]
