# Generated by Django 5.1.6 on 2025-03-13 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0016_remove_translationsrequests_date_business_reviewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target_xliff_file', models.FileField(upload_to='review_requests')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed_by_business', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(default='Created', max_length=100)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_receiver', to=settings.AUTH_USER_MODEL)),
                ('technical_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_requester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
