# Generated by Django 5.1.6 on 2025-03-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0017_reviewrequests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translations_units',
            name='language',
        ),
        migrations.RemoveField(
            model_name='translations_units',
            name='release',
        ),
    ]
