# Generated by Django 5.1.6 on 2025-03-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0018_remove_translations_units_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrequests',
            old_name='comment',
            new_name='requester_comment',
        ),
        migrations.AddField(
            model_name='reviewrequests',
            name='reviewer_comment',
            field=models.TextField(blank=True),
        ),
    ]
