# Generated by Django 5.1.6 on 2025-03-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0019_rename_comment_reviewrequests_requester_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequests',
            name='requester_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewrequests',
            name='reviewer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
