# Generated by Django 5.1.6 on 2025-03-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0020_alter_reviewrequests_requester_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translations_units',
            name='info_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
