# Generated by Django 5.1.6 on 2025-03-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0021_translations_units_info_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationsrequests',
            old_name='target_xliff_file',
            new_name='source_xliff_file_name',
        ),
        migrations.AddField(
            model_name='translationsrequests',
            name='target_xliff_file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
