# Generated by Django 5.1.6 on 2025-03-14 11:31

import xliff_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0022_rename_target_xliff_file_translationsrequests_source_xliff_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationsrequests',
            name='temp_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='translationsrequests',
            name='literalpatterns_to_exclude_file',
            field=models.FileField(upload_to=xliff_manager.models.TranslationsRequests.upload_to_folder),
        ),
        migrations.AlterField(
            model_name='translationsrequests',
            name='literals_to_exclude_file',
            field=models.FileField(upload_to=xliff_manager.models.TranslationsRequests.upload_to_folder),
        ),
        migrations.AlterField(
            model_name='translationsrequests',
            name='prompt_addition_file',
            field=models.FileField(upload_to=xliff_manager.models.TranslationsRequests.upload_to_folder),
        ),
        migrations.AlterField(
            model_name='translationsrequests',
            name='source_xliff_file',
            field=models.FileField(upload_to=xliff_manager.models.TranslationsRequests.upload_to_folder),
        ),
    ]
