# Generated by Django 5.1.6 on 2025-03-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0023_translationsrequests_temp_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translationsrequests',
            old_name='temp_path',
            new_name='dest_path',
        ),
        migrations.RenameField(
            model_name='translationsrequests',
            old_name='technical_user',
            new_name='request_user',
        ),
        migrations.RemoveField(
            model_name='translationsrequests',
            name='source_xliff_file_name',
        ),
    ]
