# Generated by Django 5.1.6 on 2025-03-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0025_alter_translationsrequests_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationsrequests',
            name='request_user',
        ),
    ]
