# Generated by Django 5.1.6 on 2025-03-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0026_remove_translationsrequests_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationsrequests',
            name='dest_path',
        ),
    ]
