# Generated by Django 5.1.6 on 2025-03-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0027_remove_translationsrequests_dest_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='translations_units',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.reviewrequests'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviewrequests',
            name='status',
            field=models.CharField(default='Requested', max_length=100),
        ),
        migrations.AlterField(
            model_name='translations_units',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
