# Generated by Django 5.1.6 on 2025-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0028_translations_units_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translations_units',
            old_name='date_modified',
            new_name='date_reviewed',
        ),
        migrations.AddField(
            model_name='translations_units',
            name='reviewer_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
