# Generated by Django 5.1.6 on 2025-03-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0029_rename_date_modified_translations_units_date_reviewed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translations_units',
            old_name='business_translation',
            new_name='reviewer_translation',
        ),
    ]
