# Generated by Django 5.1.6 on 2025-03-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0030_rename_business_translation_translations_units_reviewer_translation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
