# Generated by Django 5.1.6 on 2025-03-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0031_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translations_units',
            name='info_tag',
        ),
        migrations.AddField(
            model_name='reviewrequests',
            name='info_tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
