# Generated by Django 5.1.6 on 2025-03-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0032_remove_translations_units_info_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translations_units',
            name='ai_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
