# Generated by Django 5.1.6 on 2025-03-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0033_alter_translations_units_ai_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequests',
            name='date_declined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
