# Generated by Django 5.1.6 on 2025-03-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0034_reviewrequests_date_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequests',
            name='decline_justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
