# Generated by Django 5.1.6 on 2025-03-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0036_logdiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdiary',
            name='review_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logdiary',
            name='translation_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
