# Generated by Django 5.1.6 on 2025-03-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0037_logdiary_review_request_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logdiary',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='logdiary',
            name='accio',
            field=models.CharField(blank=True, choices=[('RRTTLLM', 'Requester_Request_Translation_to_AI'), ('TRFLLM', 'Translation_Received_from_LLM'), ('RV', 'REvision')], max_length=50, null=True),
        ),
    ]
