# Generated by Django 5.1.6 on 2025-03-26 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0039_translationsrequests_request_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInstructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('date_last_modification', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.languages')),
                ('user_last_modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_last_modification'],
            },
        ),
    ]
