# Generated by Django 5.1.6 on 2025-03-27 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xliff_manager', '0040_custominstructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequests',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.languages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translations_units',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xliff_manager.languages'),
            preserve_default=False,
        ),
    ]
