from django import forms
from django.contrib.auth.models import User

class TranslationForm(forms.Form):
    xliff_source_file = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control'}), 
        label = 'Upload the file containing the XLIFF file exported from Salesforce to be translated.',
        required=True
        
    )
    prompt_addition_file = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control'}),
        label = 'Upload the file containing the additional prompt instructions you want to provide.',
        required=False
    )
    
    literal_ids_to_exclude_file = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control'}),
        label='Upload the file containing the literals IDs that do not require translation.',
        required = False
    )
    
    literal_patterns_to_exclude_file = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control'}),
        label = 'Upload the file containing the pattterns (ex:Customlabel.Patter_to_avoid.*) that you do not want the LLM to translate.',
        required=False
    )

    """
    business_reviewer = forms.ChoiceField(
        choices=[(user.id, user.username) for user in User.objects.all()], # aIXO SEGURAMENT Cal TUnejar-ho
        widget=forms.Select(attrs={'class': 'form-select'}),
        label='Select the business reviewer that will review the translations generated by the AI.',
        required=True
    )
    """